services:
  ffmpeg-service:
    container_name: ffmpeg-service
    hostname: ffmpeg-service
    image: ghcr.io/ukck/ffmpeg-service:latest
    restart: unless-stopped
    ports:
      - "9200:8000"
    environment:
      - TMP_DIR=/tmp/ffmpeg_api
    volumes:
      - ./data:/tmp/ffmpeg_api
    networks:
      - proxy

networks:
  proxy:
    external: true